import { useState } from "react";
import { getOrCreateAuthKey, setAuthKey } from "./api/auth";
import Button from "./components/Button";
import css from "./page.module.css";

interface AuthProps {
    onDone: () => void;
}

const Auth: React.FC<AuthProps> = ({ onDone }) => {
    const [key, setKey] = useState(() => getOrCreateAuthKey());
    const [autogenerated, setAutoGenerated] = useState(true);

    function changeKey() {
        const newKey = prompt("Skriv in nyckeln:");
        if (newKey) {
            setKey(newKey);
            setAutoGenerated(false);
        }
    }

    function handleDoneClick() {
        setAuthKey(key);
        onDone();
    }

    return (
        <div className={css.container}>
            <h2>Autentisering</h2>
            <p>
                {autogenerated ?
                    "Här är en autogenererad nyckel:"
                    : "Din nyckel: "}
            </p>
            <code>{key}</code>
            {autogenerated && (
                <p>lägg till den i serverkonfigurationen.</p>
            )}
            <p>
                <span>Alternativt, ändra din nyckel: </span>
                <Button onClick={changeKey}>Ändra nyckel</Button>
            </p>
            <br />
            <Button onClick={handleDoneClick}>Klar</Button>
        </div>
    );
};

export default Auth;